postal:
  image: appjumpstart/postal:b264c5b
  # namespace: postal
  # serviceAccount: postal
  role:
    create: true
    # name: directus
  secret:
    create: true
    # name: directus
  db:
    name: postal
    user: postal
    pass: changeme
    host: mysql.mysql.svc.cluster.local
    port: "3306"
  mq:
    vhost: postal
    user: postal
    pass: changeme
    host: rabbitmq.rabbitmq.svc.cluster.local
  nginx:
    image: nginx:1.13

  # Change (probably) required:
  hosts:
    - postal.local
