postal:
  image: appjumpstart/postal:b264c5b
  # namespace: postal
  # serviceAccount: postal
  role:
    create: true
    # name: postal
  secret:
    create: true
    # name: postal
  db:
    host: mysql.mysql.svc.cluster.local
    port: "3306"
    name: postal
    user: postal
    pass: changeme
  mq:
    host: rabbitmq.rabbitmq.svc.cluster.local
    vhost: postal
    user: postal
    pass: changeme
  nginx:
    image: nginx:1.13

  # Change (probably) required:
  hosts:
    - postal.local
