{{- $fullname := include "postal.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ default $fullname .Values.postal.namespace }}
  name: {{ $fullname }}
  labels:
    app: {{ template "postal.name" . }}
    chart: {{ template "postal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  tls:
    - hosts:
      {{- range .Values.postal.hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ $fullname }}-tls
  rules:
  {{- range .Values.postal.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullname }}
              servicePort: http
  {{- end }}
