{{- if .Values.postal.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "postal.fullname" . }}
  namespace: {{ default (include "postal.fullname" .) .Values.postal.namespace }}
  labels:
    app: {{ template "postal.name" . }}
    chart: {{ template "postal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - {{ default (include "postal.fullname" .) .Values.postal.secret.name }}
    verbs: ["get"]
{{- end }}
