{{- if .Values.postal.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "postal.fullname" . }}
  labels:
    app: {{ template "postal.name" . }}
    chart: {{ template "postal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ default (include "postal.fullname" .) .Values.postal.role.name }}
subjects:
  - kind: ServiceAccount
    name: {{ default (include "postal.fullname" .) .Values.postal.serviceAccount }}
    namespace: {{ default (include "postal.fullname" .) .Values.postal.namespace }}
{{- end }}
