{{- if .Values.postal.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ default (include "postal.fullname" .) .Values.postal.namespace }}
  name: {{ default (include "postal.fullname" .) .Values.postal.secret.name }}
  labels:
    app: {{ template "postal.name" . }}
    chart: {{ template "postal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  db_pass: {{ .Values.postal.db.pass | b64enc }}
  mq_pass: {{ .Values.postal.mq.pass | b64enc }}
{{- end }}
