apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ default (include "postal.fullname" .) .Values.postal.namespace }}
  name: {{ default (include "postal.fullname" .) .Values.postal.serviceAccount }}
  labels:
    app: {{ template "postal.name" . }}
    chart: {{ template "postal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
